source 'https://rubygems.org'
source 'https://rails-assets.org'

ruby '2.1.3'

gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'jquery-rails'
gem 'rails-assets-bootstrap'
gem 'rails_helpers_code_samples', path: './../code'
gem 'high_voltage'